// The Fibonacci sequence is a series of numbers where each number is the sum of the two preceding ones, usually starting with 0 and 1.
// The sequence commonly starts with 0 and 1, and the next numbers are generated by adding the two previous numbers.

// Fibonacci Sequence using Iteration
function Fibonacci(n){
    if(n == 0 || n == 1) return n;
    else{
        var a = 0, b = 1, c;
        var  arr = [] 
        for(var i=2; i<=n ; i++){
            c = a + b;
            a = b;
            b = c;
            arr.push(c);
        }
        return c;
    }
}

console.log(Fibonacci(0)); // 0 
console.log(Fibonacci(1)); // 1
console.log(Fibonacci(10)); // 55